// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzazvjaeqquhfsbmblfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YXp2amFlcXF1aGZzYm1ibGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTcwNzQsImV4cCI6MjA2NDM5MzA3NH0.MGsLwCpgX67IICUmlR-TwaYN7cBLnlFH1AAwOWBoJ9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);